### PR TITLE
Code fixes

### PR DESCRIPTION
**Pull request by therealOri**
# Changes:

- Fixed a bug where when dragging and dropping a file into the terminal, you'd have to press "backspace" once before it worked.

- Fixed an issue where when trying to get the filename from the path given when dragging and dropping a file into the terminal it would try and split the path on `//`.  This is an issue if you use literally anything else except windows. I have added a bit of code to check to see if hyperion.py is being ran on Linux, MacOS, or Windows. If hyperion.py is being ran on any of these systems, it'll use the system appropriate/respective way of splitting a path. 

- Added a print message at the end of the main function telling people to "press enter to exit" as after the script finishes, it just hangs an waits...this confused me for a little bit.

- Added a clear() function so I can clear the terminal when working with a bunch of printing...also to make things feel/look better to use.

- Added my username to the __authors__ lists as I don't see an option for contributors. And I have added to and fixed some code.

### CODE REVIEW

**Comment by billythegoat356** [comment]
Hello.
I cannot merge your pull request as it does not bring any real improvement to Hyperion.
The only thing you improved is the input of the file.

**Comment by therealOri** [comment]
I fixed the functionality of those parts of code and fixed a couple bugs.

I clearly provided something. You're code doesn't work at all for anyone using anything else but windows. I have fixed that. But okay.

**Comment by billythegoat356** [comment]
Hyperion is an obfuscator.
The TUI is just to make it easier for people to obfuscate, so it doesn't really count. The real code here is the Hyperion class.
If you would've added some real improvements to the obfuscation itself, I would've merged the pull request without any problem.

**Comment by therealOri** [comment]
My updates were to fix the TUI and make it actually functional. (I could have left out the clear() function and use the already built in one). And I do understand what you're saying though. 

I just didn't want a non functioning terminal user interface. Especially when it gets referenced on the web based version to be used instead if your submitted code is to much/to big. It is 100% and option for people to use and I wanted to make it useable and not broken...

**Comment by billythegoat356** [comment]
Thanks!
If you have any ideas for the **obfuscation** part of Hyperion, feel free to make another pull request!
Have a nice day!

**Comment by therealOri** [comment]
If I can come up with anything or have any ideas I will!

**Pull request closed without merging**
